
SELECT 
  CASE
    WHEN nivel_ed_resumen="INFERIOR" AND IX_MEN10=0 AND linea_pobreza="debajo" THEN "SINEDUC_0_DEBAJO"
    WHEN nivel_ed_resumen="INFERIOR" AND IX_MEN10=1 AND linea_pobreza="debajo" THEN "SINEDUC_1_DEBAJO"
    WHEN nivel_ed_resumen="INFERIOR" AND IX_MEN10=2 AND linea_pobreza="debajo" THEN "SINEDUC_2_DEBAJO"
    WHEN nivel_ed_resumen="INFERIOR" AND IX_MEN10=3 AND linea_pobreza="debajo" THEN "SINEDUC_3_DEBAJO"
    WHEN nivel_ed_resumen="INFERIOR" AND IX_MEN10=4 AND linea_pobreza="debajo" THEN "SINEDUC_4_DEBAJO"
    WHEN nivel_ed_resumen="INFERIOR" AND IX_MEN10=5 AND linea_pobreza="debajo" THEN "SINEDUC_5_DEBAJO"
    WHEN nivel_ed_resumen="INFERIOR" AND IX_MEN10=6 AND linea_pobreza="debajo" THEN "SINEDUC_6_DEBAJO"
    WHEN nivel_ed_resumen="INFERIOR" AND IX_MEN10=7 AND linea_pobreza="debajo" THEN "SINEDUC_7_DEBAJO"
    WHEN nivel_ed_resumen="INFERIOR" AND IX_MEN10=0 AND linea_pobreza="sobre" THEN "SINEDUC_0_SOBRE"
    WHEN nivel_ed_resumen="INFERIOR" AND IX_MEN10=1 AND linea_pobreza="sobre" THEN "SINEDUC_1_SOBRE"
    WHEN nivel_ed_resumen="INFERIOR" AND IX_MEN10=2 AND linea_pobreza="sobre" THEN "SINEDUC_2_SOBRE"
    WHEN nivel_ed_resumen="INFERIOR" AND IX_MEN10=3 AND linea_pobreza="sobre" THEN "SINEDUC_3_SOBRE"
    WHEN nivel_ed_resumen="INFERIOR" AND IX_MEN10=4 AND linea_pobreza="sobre" THEN "SINEDUC_4_SOBRE"
    WHEN nivel_ed_resumen="INFERIOR" AND IX_MEN10=5 AND linea_pobreza="sobre" THEN "SINEDUC_5_SOBRE"
    WHEN nivel_ed_resumen="INFERIOR" AND IX_MEN10=6 AND linea_pobreza="sobre" THEN "SINEDUC_6_SOBRE"
    WHEN nivel_ed_resumen="INFERIOR" AND IX_MEN10=7 AND linea_pobreza="sobre" THEN "SINEDUC_7_SOBRE"
    WHEN nivel_ed_resumen="SECUNDARIO" AND IX_MEN10=0 AND linea_pobreza="debajo" THEN "SECUNDARIO_0_DEBAJO"
    WHEN nivel_ed_resumen="SECUNDARIO" AND IX_MEN10=1 AND linea_pobreza="debajo" THEN "SECUNDARIO_1_DEBAJO"
    WHEN nivel_ed_resumen="SECUNDARIO" AND IX_MEN10=2 AND linea_pobreza="debajo" THEN "SECUNDARIO_2_DEBAJO"
    WHEN nivel_ed_resumen="SECUNDARIO" AND IX_MEN10=3 AND linea_pobreza="debajo" THEN "SECUNDARIO_3_DEBAJO"
    WHEN nivel_ed_resumen="SECUNDARIO" AND IX_MEN10=4 AND linea_pobreza="debajo" THEN "SECUNDARIO_4_DEBAJO"
    WHEN nivel_ed_resumen="SECUNDARIO" AND IX_MEN10=5 AND linea_pobreza="debajo" THEN "SECUNDARIO_5_DEBAJO"
    WHEN nivel_ed_resumen="SECUNDARIO" AND IX_MEN10=6 AND linea_pobreza="debajo" THEN "SECUNDARIO_6_DEBAJO"
    WHEN nivel_ed_resumen="SECUNDARIO" AND IX_MEN10=7 AND linea_pobreza="debajo" THEN "SECUNDARIO_7_DEBAJO"
    WHEN nivel_ed_resumen="SECUNDARIO" AND IX_MEN10=0 AND linea_pobreza="sobre" THEN "SECUNDARIO_0_SOBRE"
    WHEN nivel_ed_resumen="SECUNDARIO" AND IX_MEN10=1 AND linea_pobreza="sobre" THEN "SECUNDARIO_1_SOBRE"
    WHEN nivel_ed_resumen="SECUNDARIO" AND IX_MEN10=2 AND linea_pobreza="sobre" THEN "SECUNDARIO_2_SOBRE"
    WHEN nivel_ed_resumen="SECUNDARIO" AND IX_MEN10=3 AND linea_pobreza="sobre" THEN "SECUNDARIO_3_SOBRE"
    WHEN nivel_ed_resumen="SECUNDARIO" AND IX_MEN10=4 AND linea_pobreza="sobre" THEN "SECUNDARIO_4_SOBRE"
    WHEN nivel_ed_resumen="SECUNDARIO" AND IX_MEN10=5 AND linea_pobreza="sobre" THEN "SECUNDARIO_5_SOBRE"
    WHEN nivel_ed_resumen="SECUNDARIO" AND IX_MEN10=6 AND linea_pobreza="sobre" THEN "SECUNDARIO_6_SOBRE"
    WHEN nivel_ed_resumen="SECUNDARIO" AND IX_MEN10=7 AND linea_pobreza="sobre" THEN "SECUNDARIO_7_SOBRE"
    WHEN nivel_ed_resumen="UNIVERSITARIO" AND IX_MEN10=0 AND linea_pobreza="debajo" THEN "UNIVERSITARIO_0_DEBAJO"
    WHEN nivel_ed_resumen="UNIVERSITARIO" AND IX_MEN10=1 AND linea_pobreza="debajo" THEN "UNIVERSITARIO_1_DEBAJO"
    WHEN nivel_ed_resumen="UNIVERSITARIO" AND IX_MEN10=2 AND linea_pobreza="debajo" THEN "UNIVERSITARIO_2_DEBAJO"
    WHEN nivel_ed_resumen="UNIVERSITARIO" AND IX_MEN10=3 AND linea_pobreza="debajo" THEN "UNIVERSITARIO_3_DEBAJO"
    WHEN nivel_ed_resumen="UNIVERSITARIO" AND IX_MEN10=4 AND linea_pobreza="debajo" THEN "UNIVERSITARIO_4_DEBAJO"
    WHEN nivel_ed_resumen="UNIVERSITARIO" AND IX_MEN10=5 AND linea_pobreza="debajo" THEN "UNIVERSITARIO_5_DEBAJO"
    WHEN nivel_ed_resumen="UNIVERSITARIO" AND IX_MEN10=6 AND linea_pobreza="debajo" THEN "UNIVERSITARIO_6_DEBAJO"
    WHEN nivel_ed_resumen="UNIVERSITARIO" AND IX_MEN10=7 AND linea_pobreza="debajo" THEN "UNIVERSITARIO_7_DEBAJO"
    WHEN nivel_ed_resumen="UNIVERSITARIO" AND IX_MEN10=0 AND linea_pobreza="sobre" THEN "UNIVERSITARIO_0_SOBRE"
    WHEN nivel_ed_resumen="UNIVERSITARIO" AND IX_MEN10=1 AND linea_pobreza="sobre" THEN "UNIVERSITARIO_1_SOBRE"
    WHEN nivel_ed_resumen="UNIVERSITARIO" AND IX_MEN10=2 AND linea_pobreza="sobre" THEN "UNIVERSITARIO_2_SOBRE"
    WHEN nivel_ed_resumen="UNIVERSITARIO" AND IX_MEN10=3 AND linea_pobreza="sobre" THEN "UNIVERSITARIO_3_SOBRE"
    WHEN nivel_ed_resumen="UNIVERSITARIO" AND IX_MEN10=4 AND linea_pobreza="sobre" THEN "UNIVERSITARIO_4_SOBRE"
    WHEN nivel_ed_resumen="UNIVERSITARIO" AND IX_MEN10=5 AND linea_pobreza="sobre" THEN "UNIVERSITARIO_5_SOBRE"
    WHEN nivel_ed_resumen="UNIVERSITARIO" AND IX_MEN10=6 AND linea_pobreza="sobre" THEN "UNIVERSITARIO_6_SOBRE"
    WHEN nivel_ed_resumen="UNIVERSITARIO" AND IX_MEN10=7 AND linea_pobreza="sobre" THEN "UNIVERSITARIO_7_SOBRE"
    ELSE "RESTO"
  END AS NIVELED_HIJOS_LINEAPOBREZA,
COUNT(*)
FROM 
  `disco-parsec-461018-f6.capstone.matriz16`
GROUP BY NIVELED_HIJOS_LINEAPOBREZA
