CREATE TABLE IF NOT EXISTS capstone.matriz16
AS
SELECT *,
CASE
  WHEN NIVEL_ED=4 THEN "SECUNDARIO"
  WHEN NIVEL_ED=5 THEN "SECUNDARIO"
  WHEN NIVEL_ED=6 THEN "UNIVERSITARIO"
  ELSE "INFERIOR"
END AS nivel_ed_resumen
FROM
  `disco-parsec-461018-f6.capstone.final_16`  